import type { Lead, DailyPriority } from '@/types';
import { LeadType, LeadStatus } from '@/types';

export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    name: 'TechCorp Solutions',
    organization: 'TechCorp',
    contactPerson: 'Sarah Jenkins',
    role: 'HR Director',
    email: 'sarah.j@techcorp.com',
    phone: '555-0123',
    linkedinUrl: 'https://linkedin.com/in/sarahjenkins',
    website: 'https://techcorp.com',
    type: LeadType.Corporate,
    source: 'LinkedIn',
    status: LeadStatus.ProposalNeeded,
    opportunityValue: 15000,
    offerInterest: ['Team Alignment Workshop', 'Executive Coaching'],
    notes: 'Very interested in improving leadership culture after recent merger.',
    lastContactDate: '2026-04-28',
    nextFollowUpDate: '2026-05-03',
    recommendedNextAction: 'Send Team Alignment proposal',
    isHot: true,
    createdAt: '2026-04-15',
  },
  {
    id: '2',
    name: 'Grace Community Church',
    organization: 'Grace Community',
    contactPerson: 'Pastor Mark Smith',
    role: 'Senior Pastor',
    email: 'mark@gracecommunity.org',
    phone: '555-0456',
    linkedinUrl: '',
    website: 'https://gracecommunity.org',
    type: LeadType.Church,
    source: 'Referral',
    status: LeadStatus.CallBooked,
    opportunityValue: 5000,
    offerInterest: ['Leadership Development Series'],
    notes: 'Looking for mentorship for their youth leadership team.',
    lastContactDate: '2026-05-01',
    nextFollowUpDate: '2026-05-04',
    recommendedNextAction: 'Prepare discovery questions for tomorrow\'s call',
    isHot: false,
    createdAt: '2026-04-20',
  },
  {
    id: '3',
    name: 'Global Edu Group',
    organization: 'Global Edu',
    contactPerson: 'Dr. Linda Wu',
    role: 'Dean of Faculty',
    email: 'l.wu@globaledu.univ',
    phone: '555-0789',
    linkedinUrl: 'https://linkedin.com/in/lindawu',
    website: 'https://globaledu.univ',
    type: LeadType.University,
    source: 'Speaking Engagement',
    status: LeadStatus.Contacted,
    opportunityValue: 25000,
    offerInterest: ['Strategic Leadership Advisory'],
    notes: 'Interested in a year-long advisory contract for their leadership team.',
    lastContactDate: '2026-04-30',
    nextFollowUpDate: '2026-05-03',
    recommendedNextAction: 'Follow up on the initial outreach message',
    isHot: true,
    createdAt: '2026-04-25',
  },
  {
    id: '4',
    name: 'Starlight Non-Profit',
    organization: 'Starlight',
    contactPerson: 'James Wilson',
    role: 'Executive Director',
    email: 'j.wilson@starlight.org',
    phone: '555-0999',
    linkedinUrl: 'https://linkedin.com/in/jwilson',
    website: 'https://starlight.org',
    type: LeadType.Nonprofit,
    source: 'Website',
    status: LeadStatus.DiscoveryCompleted,
    opportunityValue: 8000,
    offerInterest: ['Innovation and Growth Strategy'],
    notes: 'Needs help scaling operations after a large grant.',
    lastContactDate: '2026-05-02',
    nextFollowUpDate: '2026-05-05',
    recommendedNextAction: 'Draft proposal for strategy session',
    isHot: false,
    createdAt: '2026-04-28',
  },
  {
    id: '5',
    name: 'David’s Mighty 3 Candidate',
    organization: 'Individual',
    contactPerson: 'Michael Brown',
    role: 'Business Owner',
    email: 'michael.b@gmail.com',
    phone: '555-1111',
    linkedinUrl: 'https://linkedin.com/in/mbrown',
    website: '',
    type: LeadType.DM3,
    source: 'Social Media',
    status: LeadStatus.Replied,
    opportunityValue: 2000,
    offerInterest: ['David’s Mighty 3 Mentorship'],
    notes: 'Interested in the spiritual leadership aspect.',
    lastContactDate: '2026-05-02',
    nextFollowUpDate: '2026-05-03',
    recommendedNextAction: 'Invite to the next Sharpening Room session',
    isHot: true,
    createdAt: '2026-05-01',
  }
];

export const MOCK_PRIORITIES: DailyPriority[] = [
  {
    id: 'p1',
    action: 'Send Proposal to Sarah Jenkins (TechCorp)',
    reason: 'High-value opportunity ($15k) waiting for proposal.',
    leadId: '1',
    priority: 'High',
  },
  {
    id: 'p2',
    action: 'Follow up with Dr. Linda Wu (Global Edu)',
    reason: 'Contacted 3 days ago, no reply yet. Hot lead.',
    leadId: '3',
    priority: 'High',
  },
  {
    id: 'p3',
    action: 'Invite Michael Brown to Sharpening Room',
    reason: 'Expressed interest in DM3 yesterday.',
    leadId: '5',
    priority: 'Medium',
  },
  {
    id: 'p4',
    action: 'Prepare for Discovery Call with Pastor Mark Smith',
    reason: 'Call scheduled for tomorrow at 10 AM.',
    leadId: '2',
    priority: 'Medium',
  },
  {
    id: 'p5',
    action: 'Review pipeline for overdue follow-ups',
    reason: 'Maintain revenue momentum.',
    priority: 'Low',
  }
];
